name: Java CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/test.csv & echo 'basak'
      - run: touch starting_build_actionscheckout@v3_10
      - uses: actions/checkout@v3
      - run: touch starting_build_SetupJDK8_11
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: touch starting_build_Buildmodules_16
      - name: Build modules
        run: gradle clean build
